# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
